name: 'Setup Python Environment'
description: 'Setup Python 3.11 and install dependencies (checkout must happen first)'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
